import { build } from 'esbuild';
import { writeFile } from 'node:fs/promises';

const result = await build({
    entryPoints: ['hack-source.js'],
    bundle: true,
    format: 'esm',
    platform: 'browser',
    target: 'es2020',
    write: false,
    logLevel: 'silent'
});

let code = result.outputFiles[0].text.trim();

const exportMatch = code.match(/\nexport\s*\{\s*([A-Za-z0-9_$]+)\s+as\s+default\s*\};?\s*$/u);

if(!exportMatch)
{
    throw new TypeError('Expected bundled hack output to end with a default export.');
}

code = code.replace(/\nexport\s*\{\s*[A-Za-z0-9_$]+\s+as\s+default\s*\};?\s*$/u, '');

const wrapped = `// Generated by build-hack.mjs. Do not edit this file directly.\n(() => {\n${code}\nreturn ${exportMatch[1]};\n})()\n`;

await writeFile('hack.js', wrapped);
